/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.client.services;
	
import javax.inject.Inject;
import javax.inject.Named;
import org.granite.client.messaging.RemoteAlias;
import org.granite.client.tide.server.ServerSession;

@Named
@RemoteAlias("com.wineshop.services.WelcomeService")
public class WelcomeService extends WelcomeServiceBase {
	
	@Inject
	public WelcomeService(ServerSession serverSession) {
    	super(serverSession);
    }
}
