/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.client.entities;

import org.granite.client.messaging.RemoteAlias;
import org.granite.messaging.annotations.Serialized;

@Serialized
@RemoteAlias("com.wineshop.entities.Address")
public class Address extends AddressBase {

    private static final long serialVersionUID = 1L;
}