/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.wineshop.client.entities;

import org.granite.client.messaging.RemoteAlias;

@RemoteAlias("com.wineshop.entities.Wine$Type")
public enum Wine$Type {

    RED, 
    WHITE, 
    ROSE
}
